import type { ProjectStorage } from '../server/contracts.js'
import { R2ProjectStorage } from './r2-storage.js'
import { S3ObjectStorage } from './s3-storage.js'

export type ObjectHead = {
  size: number
  etag: string
  contentType: string | null
  customMetadata: Record<string, string>
}

export type ObjectBody = ObjectHead & {
  body: ReadableStream<Uint8Array>
}

/**
 * Cloud object-storage boundary used by uploads, share delivery and cleanup.
 *
 * Self-hosted deployments can provide another adapter (S3, MinIO, OSS, COS)
 * without changing the HTTP routes or the D1 quota/cleanup ledger. Object keys
 * are generated by BlendProof and must be treated as opaque exact keys.
 */
export interface ObjectStorage extends ProjectStorage {
  readonly provider: string
  headObject(key: string): Promise<ObjectHead | null>
  getObject(key: string): Promise<ObjectBody | null>
  deleteObject(key: string | string[]): Promise<void>
}

export type ObjectStorageEnv = {
  ASSETS: R2Bucket
  STORAGE_PROVIDER?: string
  S3_ENDPOINT?: string
  S3_REGION?: string
  S3_ACCESS_KEY_ID?: string
  S3_SECRET_ACCESS_KEY?: string
  S3_SESSION_TOKEN?: string
}

/** Single composition root for the production object-storage adapter. */
export function objectStorage(env: ObjectStorageEnv): ObjectStorage {
  if (env.STORAGE_PROVIDER === 's3') {
    if (!env.S3_ENDPOINT || !env.S3_REGION || !env.S3_ACCESS_KEY_ID || !env.S3_SECRET_ACCESS_KEY) {
      throw new Error('S3 对象存储配置不完整。')
    }
    return new S3ObjectStorage({
      endpoint: env.S3_ENDPOINT,
      region: env.S3_REGION,
      accessKeyId: env.S3_ACCESS_KEY_ID,
      secretAccessKey: env.S3_SECRET_ACCESS_KEY,
      sessionToken: env.S3_SESSION_TOKEN,
    })
  }
  return new R2ProjectStorage(env.ASSETS)
}

export function objectStorageHealth(env: Partial<ObjectStorageEnv>) {
  const provider = env.STORAGE_PROVIDER === 's3' ? 's3' : 'r2'
  return {
    provider,
    bound: provider === 's3'
      ? Boolean(env.S3_ENDPOINT && env.S3_REGION && env.S3_ACCESS_KEY_ID && env.S3_SECRET_ACCESS_KEY)
      : Boolean(env.ASSETS),
  }
}
